config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers: { sessions: 'devise_logins' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :usuarios do
    authenticated  do
      root to: 'patients#index'
    end

    unauthenticated do
      root to: 'users#login', as: 'unauthenticated_root'
    end
  end

  resources :patients do
    collection do
      get 'print'
    end
    resources :evolutions, except: [:show]
    collection do
      patch 'update'
      get 'clinic_history'
      post 'create_clinic_history'
      patch 'update_clinic_history'
      get 'search_data'
      post 'import_data'
    end
  end

  resources :cardiopulmonar, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :musculoesqueletico, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :services  do
    collection do
      post 'save_company_logo'
      get 'specials_tests'
      get 'flex_tests'
      get 'neuro_test'
    end
  end

  # Nuevas funcionalidades 03-10-2017

  namespace :fisio do
    resources :patients do
      resources :evoluciones
      resources :clinic_histories, except: [:destroy] do
        resources :desarrollo_motores, except: [:index, :show, :destroy]
        resources :sistema_cardiopulmonar, except: [:index, :show, :destroy]
        resources :sistema_musculoesqueletico, except: [:index, :show, :destroy]
        resources :sistema_neuromuscular, except: [:index, :show, :destroy] do
          collection do
            post 'create_extra'
            put 'update_extra'
          end
        end
        resources :remision_externa, except: [:index, :show, :destroy]
        resources :sistema_tegumentario, except: [:index, :show, :destroy]
        resources :pruebas_especiales, except: [:index, :show, :destroy]
        resources :sistema_genitourinario, except: [:index, :show, :destroy]
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
          end
        end
      end
    end
  end

  namespace :medical do
    resources :patients do
      resources :historia_medicas, except: [:destroy] do
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
            get 'formulacion'
          end
        end
      end
    end
  end
end

app/controllers/medical/historia_medicas_controller.rb
module Medical
  class HistoriaMedicasController < MedicalController
    before_action :set_patient
    before_action :set_history, only: [:edit, :update]

    def index
      @histories = @patient.historia_medicas.order('created_at desc')
      .paginate(page: params[:page], per_page: 15)
    end

    def new
      @history = @patient.historia_medicas.new
      @history.impresion_diagnosticas.build
    end

    def edit
      @history.impresion_diagnosticas.build if @history.impresion_diagnosticas.count == 0
    end

    def create
      @history = HistoriaMedica.new(history_params)
      if @history.save
        flash[:notice] = "Historia clínica creada"
        redirect_to edit_medical_patient_historia_medica_path(@patient, @history)
      else
        render :new
      end
    end

    # editar historia solo hasta 15 minutos despues
    def update
      if  (Time.now - 15.minutes) > @history.created_at
        @history.errors.add("Tiempo", "Solo puede realizar cambios hasta 15 minutos después de crear la historia clíinica.")
        render :edit
      else
        if @history.update(history_params)
          flash[:notice] = "Información actualizada"
          redirect_to edit_medical_patient_historia_medica_path(@patient, @history)
        else
          render :edit
        end
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaMedica.find(params[:id])
    end

    # parametros fuertes
    def history_params
      params.require(:historia_medica).permit(:id, :paciente_id, :motivo_consulta, :piel_faneras,
        :historia_actual, :antecedente_medico, :antecedente_quirurgico, :antecedente_ginecoobstetrico,
        :antecedente_alergia, :revision_sistemas, :imagenes, :laboratorios, :exploracion_fisica,
        :inspeccion_general, :cabeza, :cuello, :torax, :abdomen, :genitales, :extremidades, :neurologico,
        :mental, :analisis, :plan, :intervencion_terapeutica, :formulacion, :control,
        :ta, :fc, :fr, :sato2, :peso, :talla, :glucometria, :imc, :temperatura, :unidad_talla,
        impresion_diagnosticas_attributes: [:id, :historia_medica_id, :descripcion, :_destroy])
    end
  end
end

app/controllers/medical/patients_controller.rb
module Medical
  class PatientsController < MedicalController
    before_action :set_patient, except: [:new, :create]

    # crear nuevo paciente
    def new
      @patient = current_usuario.pacientes.new
    end

    def create
      @patient = Paciente.new(patient_params)
      if @patient.save
        flash[:notice] = "Paciente creado correctamente"
        redirect_to edit_medical_patient_path(@patient)
      else
        render :new
      end
    end

    def show
    end

    # formulario de edición
    def edit
    end

    # edición de datos
    def update
      if @patient.update(patient_params)
        flash[:notice] = "Paciente editado"
        redirect_to edit_medical_patient_path(@patient)
      else
        render :edit
      end
    end

    private

    def set_patient
      @patient = current_usuario.pacientes.find(params[:id])
    end

    def patient_params
      params.require(:paciente).permit(:id, :usuario_id, :estado_civil_id,
      :fecha_actual, :direccion, :edad, :genero, :telefono, :movil, :rh, :membership_id,
      :profesion, :nombre_acompanante, :movil_acompanante, :remitido_por, :eps, :email,
      :type_document_id, :telefono, :escolaridad, :documento, :nombre, :fecha_nacimiento)
    end
  end
end

app/controllers/medical/print_controller.rb
module Medical
  class PrintController < MedicalController
    before_action :set_patient
    before_action :set_history
    
    def single
      respond_to do |format|
        format.html
        format.pdf do
          render template: "medical/historia_medicas/print", pdf: "#{@patient.nombre}-Historia Clinica-#{@history.created_at.strftime('%d-%m-%Y')}",
          encoding: 'utf-8', :margin => {:bottom => 22}, footer:  { html: {   template:'shared/pdf_footer' } }
        end
      end
    end

    # solo campo formulación
    def formulacion
      respond_to do |format|
        format.html
        format.pdf do
          render template: "medical/historia_medicas/print_formulacion", pdf: "#{@patient.nombre}-Formulación-#{@history.created_at.strftime('%d-%m-%Y')}",
          encoding: 'utf-8', :margin => {:bottom => 22}, footer:  { html: {   template:'shared/pdf_footer' } }
        end
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaMedica.where(id: params[:historia_medica_id]).includes(:impresion_diagnosticas).first
    end
  end
end

app/controllers/medical_controller.rb
# modulo fisio, clase generadora de controladores
class MedicalController < ApplicationController
  before_action :authenticate_usuario!
  before_action :check_module

  layout "medical/layouts/application"

  protected

  # validar acceso solo usuarios con este modulo
  def check_module
    service = current_usuario.user_services.find_by(service_id: 1)
    if service.nil?
      redirect_to root_path, alert: 'No tiene acceso a ese módulo.'
    end
  end
end

app/views/medical/layouts/_historia_actual.html.erb
<div class="pull-right info-header-user">
  <%= @patient.nombre%> 
  <small><a href="<%=edit_medical_patient_historia_medica_path(@patient, @history)%>" title="Ver historia">
    <i class="fa fa-search"></i> 
  </a></small>
  <small><%=@history.created_at.strftime("%Y-%m-%d %I:%M %p") %></small>
</div>

app/views/medical/layouts/_left_menu.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "" %>
      </div>
      <div class="pull-left info">
        <p><%=current_usuario.nombre %></p>
        <a href="<%=root_path%>"><i class="fa fa-circle text-success"></i> Ir a consultorio</a>
      </div>
    </div>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">GESTIÓN DEL PACIENTE</li>

      <li class="<%= $menu == "company" || $menu == "membership" || $menu=="invoice" ? 'active' : ''%>">
        <%-if @patient.new_record? %>
          <a href="#">
            <i class="fa fa-cog"></i> <span>Paciente</span>
          </a>
        <%else%>
          <a href="<%= edit_medical_patient_path(@patient)%>">
            <i class="fa fa-cog"></i> <span>Paciente</span>
          </a>
        <%end%>
      </li>
      <%-unless @patient.id.nil?%>
        <li class="<%= $menu == "company" || $menu == "membership" || $menu=="invoice" ? 'active' : ''%>">
          <a href="<%=medical_patient_historia_medicas_path(@patient)%>">
            <i class="fa fa-cog"></i> <span>Historias clínicas</span>
          </a>
        </li>
        <%-if @patient.historia_clinicas.count > 0 && !@history.nil? && !@history.new_record?%>
          <hr>
          <li class="">
            <a href="">
              <i class="fa fa-cog"></i> <span>Desarrollo Motor</span>
            </a>
          </li>
        <%end%>
      <%end%>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/medical/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- ng-app="SensationApp" -->
<head>
  <title>HistoriaClínica</title>
  <%= csrf_meta_tags %>

  <meta content="initial-scale=1, maximum-scale=1" name="viewport"/>
  <meta name="theme-color" content="#1199d3">
  <!-- Windows Phone -->
  <meta name="msapplication-navbutton-color" content="#1199d3">
  <!-- iOS Safari -->
  <meta name="apple-mobile-web-app-status-bar-style" content="#1199d3">

  <%= stylesheet_link_tag    'adminlte/application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'adminlte/application', 'data-turbolinks-track'=> 'reload' %>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
</head>

<body class="hold-transition skin-blue sidebar-mini">

  <script type="text/javascript">
    $(document).ready(function() {
      $.AdminLTE.layout.activate();
    });

    $(document).on('page:load', function() {
      var o;
      o = $.AdminLTE.options;
      if (o.sidebarPushMenu) {
        $.AdminLTE.pushMenu.activate(o.sidebarToggleSelector);
      }
      $.AdminLTE.layout.activate();
    });
  </script>
    
  <%-if alert %>
    <div class="alert alert-danger alert-dismissible no-print">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4><i class="icon fa fa-ban"></i> Alerta!</h4>
      <%= alert %>
    </div>
  <%end%>
  

  <%-if notice%>
    <div class="alert alert-success alert-dismissible no-print">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4><i class="icon fa fa-check"></i> Exito!</h4>
      <%=notice%>
    </div>
  <%end%>


  <div class="wrapper">

    <header class="main-header">
      <!-- Logo -->
      <a href="<%= root_path %>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>H</b>C</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Historia</b>ClÍNICA</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <!--<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">-->
        <a href="#" class="sidebar-toggle sidebar-toggle-large" role="button" onclick="toggle_menu()">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <!-- Sidebar toggle button responsive -->
        <a href="#" class="sidebar-toggle sidebar-toggle-small" role="button" onclick="toggle_menu_small()">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- User Account: style can be found in dropdown.less -->
            <li class=" user user-menu">
              <a href="#" class="dropdown-toggle">
                <%- if !current_usuario.logo_empresa.url.nil? %>
                  <%= image_tag current_usuario.logo_empresa.url, class: "user-image", alt: "User Image" %>
                <% end %>  
                <span class="hidden-xs"><%= current_usuario.nombre %></span>
              </a>
            </li>
            <li>
              <a href="<%= destroy_usuario_session_path%>" data-method="delete" ><i class="fa fa-sign-out"></i>Cerrar sesión</a>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <!--
            <li>
              <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li>-->
          </ul>
        </div>
      </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <%=render 'medical/layouts/left_menu' %>
    
    <div class="content-wrapper">
      <%= yield %>
    </div>

    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
      </div>
      <strong>Historia clínica.</strong>

      <a class="link-license" data-toggle="modal" data-target="#myModal">  
        Acuerdo de uso y licencia
      </a>
      
      <!--
      <strong>Copyright &copy; 2014-2016 <a href="#">Almsaeed Studio</a>.</strong> All rights
      reserved.-->
    </footer>
  </div>
  <%= render template: 'layouts/license' %>
</body>
</html>