config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers: { sessions: 'devise_logins' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :usuarios do
    authenticated  do
      root to: 'patients#index'
    end

    unauthenticated do
      root to: 'users#login', as: 'unauthenticated_root'
    end
  end

  resources :patients do
    collection do
      get 'print'
    end
    resources :evolutions, except: [:show]
    collection do
      patch 'update'
      get 'clinic_history'
      post 'create_clinic_history'
      patch 'update_clinic_history'
      get 'search_data'
      post 'import_data'
    end
  end

  resources :cardiopulmonar, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :musculoesqueletico, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :services  do
    collection do
      post 'save_company_logo'
      get 'specials_tests'
      get 'flex_tests'
      get 'neuro_test'
    end
  end

  # Nuevas funcionalidades 03-10-2017

  namespace :fisio do
    resources :patients do
      resources :evoluciones
      resources :clinic_histories, except: [:destroy] do
        resources :desarrollo_motores, except: [:index, :show, :destroy]
        resources :sistema_cardiopulmonar, except: [:index, :show, :destroy]
        resources :sistema_musculoesqueletico, except: [:index, :show, :destroy]
        resources :sistema_neuromuscular, except: [:index, :show, :destroy] do
          collection do
            post 'create_extra'
            put 'update_extra'
          end
        end
        resources :remision_externa, except: [:index, :show, :destroy]
        resources :sistema_tegumentario, except: [:index, :show, :destroy]
        resources :pruebas_especiales, except: [:index, :show, :destroy]
        resources :sistema_genitourinario, except: [:index, :show, :destroy]
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
          end
        end
      end
    end
  end

  namespace :medical do
    resources :patients do
      resources :historia_medicas, except: [:destroy] do
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
            get 'formulacion'
          end
        end
      end
    end
  end
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  #belongs_to :sistema_neuromuscular
  belongs_to :historia_clinica
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cadera.rb
class Cadera < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
end

app/models/cuello.rb
class Cuello < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/daniel.rb
class Daniel < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/dolor.rb
class Dolor < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/edema.rb
class Edema < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/evolucion.rb
class Evolucion < ActiveRecord::Base
  belongs_to :paciente
end

app/models/hombro.rb
class Hombro < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/memorium.rb
class Memorium < ActiveRecord::Base
  #belongs_to :sistema_neuromuscular
  belongs_to :historia_clinica
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :estado_civil
  belongs_to :type_document

  has_many :evolucions, dependent: :destroy
  has_many :historia_clinicas, dependent: :destroy
  has_many :historia_medicas, dependent: :destroy

  #validates :genero, presence: true

  # busqueda predictiva de pacientes
  def self.search_filter(param)
    param = param.parameterize.underscore.humanize.downcase
    where("LOWER(pacientes.documento) ILIKE('%#{param}%') "\
    "OR LOWER(pacientes.email) ILIKE('%#{param}%') "\
    "OR LOWER(pacientes.nombre) ILIKE('%#{param}%')")
  end

  # búsqueda de paciente por documento o email
  def self.search_by_term(term)
    joins('LEFT JOIN memberships ON pacientes.membership_id = memberships.id')
    .where("pacientes.documento ILIKE('%#{term}%') "\
    "OR LOWER(pacientes.email) ILIKE('%#{term.downcase}%') "\
    "OR LOWER(pacientes.nombre) ILIKE('%#{term.downcase}%') ")
    .select('pacientes.id, pacientes.nombre, pacientes.email, pacientes.membership_id, memberships.name as membership_name, memberships.price as membership_price')
  end
end

app/models/perimetro.rb
class Perimetro < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/perinatale.rb
class Perinatale < ActiveRecord::Base
  belongs_to :historia_clinica
end

app/models/postura.rb
class Postura < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/prenatale.rb
class Prenatale < ActiveRecord::Base
  belongs_to :historia_clinica
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :user_services
  has_many :usuarios, through: :user_services
end

app/models/tronco.rb
class Tronco < ActiveRecord::Base
  belongs_to :sistema_musculoesqueletico
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_base64_uploader :logo_empresa, UserImageUploader
  mount_uploader :firma_digital, UserImageUploader

  has_many :pacientes

  has_many :user_services
  has_many :services, through: :user_services

  accepts_nested_attributes_for :user_services, reject_if: :all_blank,  allow_destroy: true
end

app/views/partials/top_menu.html.haml
%nav.navbar.navbar-default.top_menu
  .container1
    .pull-left
      %h3 
        =link_to 'SportMedic', root_path
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button', 'data-toggle'=>'collapse', 'data-target'=>'#bs-example-navbar-collapse-1', 'aria-expanded'=>'false'}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        %li
          =link_to 'Inicio', root_path
        -if @patient.id.nil?
          %li.active
            %a{ href: "#{clinic_history_patients_path }" } Historia Clínica
        -else
          %li.active
            %a{ href: "#{clinic_history_patients_path(id: @patient.id) }" } Historia Clínica
          %li
            =link_to 'Evolución', patient_evolutions_path(patient_id: @patient.id)

      %ul.pull-right.nav.navbar-nav
        %li
          =link_to 'Cerrar Sesión', destroy_usuario_session_path, method: :delete

app/views/shared/pdf_footer.pdf.haml
-# ***********
-# OJO, por defecto coloqué 25 de morgin para el footer, el contenido de este archivo no debe superar esa medida
-# para cambiarlo se debe ir a app/controllers/patients_controlle.rb -> print
-# **********

%hr{style: 'border-top: 1px solid #333; margin-bottom:1px'}
.footer{style: 'height: 45px; padding: 1px 10px; margin-top: 0; width:100%'}
  %div{style: 'display: inline-block; width: 20%; margin-top: 0; height: 45px;'}
    =wicked_pdf_image_tag 'bgGrayFooter.png', height: '45', width: '100%'
  -if current_usuario.firma_digital.url.nil?

    %div{style: 'display: inline-block; width: 58%; text-align: center'}
      %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
        T. Profesional:
        =current_usuario.tarjeta_profesional
      %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
        Tel: 
        ="#{current_usuario.telefono}"
      %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
        E-mail: 
        =current_usuario.email
      %p{style: 'margin: 3px; color: #272525; font-family:Arial; font-size: 10px;'}
        =current_usuario.direccion
  
  -else
    %div{style: 'display: inline-block; width: 58%; text-align: center'}
      %div{style: 'display: inline-block; width: 48%; text-align: center'}
        %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
          T. Profesional:
          =current_usuario.tarjeta_profesional
        %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
          Tel: 
          ="#{current_usuario.telefono}"
        %p{style: 'margin: 2px; color: #272525; font-family:Arial; font-size: 10px;'}
          E-mail: 
          =current_usuario.email
        %p{style: 'margin: 3px; color: #272525; font-family:Arial; font-size: 10px;'}
          =current_usuario.direccion
      %div{style: 'display: inline-block; width: 48%; text-align: center'}
        =wicked_pdf_image_tag current_usuario.firma_digital.url, height: '33', style: 'margin: 2px;'
        %hr{style: 'margin: 2px 0'}
        %p{style: 'margin: 0 2px; color: #272525; font-family:Arial; font-size: 10px;'}
          Firma

  %div{style: 'display: inline-block; width: 20%; margin-top: 0; height: 45px;'}
    =wicked_pdf_image_tag 'bgGrayFooter2.png', height: '45', width: '100%'