config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios, controllers: { sessions: 'devise_logins' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :usuarios do
    authenticated  do
      root to: 'patients#index'
    end

    unauthenticated do
      root to: 'users#login', as: 'unauthenticated_root'
    end
  end

  resources :patients do
    collection do
      get 'print'
    end
    resources :evolutions, except: [:show]
    collection do
      patch 'update'
      get 'clinic_history'
      post 'create_clinic_history'
      patch 'update_clinic_history'
      get 'search_data'
      post 'import_data'
    end
  end

  resources :cardiopulmonar, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :musculoesqueletico, only: [:create, :update] do
    collection do
      patch 'update'
    end
  end

  resources :services  do
    collection do
      post 'save_company_logo'
      get 'specials_tests'
      get 'flex_tests'
      get 'neuro_test'
    end
  end

  # Nuevas funcionalidades 03-10-2017

  namespace :fisio do
    resources :patients do
      resources :evoluciones
      resources :clinic_histories, except: [:destroy] do
        resources :desarrollo_motores, except: [:index, :show, :destroy]
        resources :sistema_cardiopulmonar, except: [:index, :show, :destroy]
        resources :sistema_musculoesqueletico, except: [:index, :show, :destroy]
        resources :sistema_neuromuscular, except: [:index, :show, :destroy] do
          collection do
            post 'create_extra'
            put 'update_extra'
          end
        end
        resources :remision_externa, except: [:index, :show, :destroy]
        resources :sistema_tegumentario, except: [:index, :show, :destroy]
        resources :pruebas_especiales, except: [:index, :show, :destroy]
        resources :sistema_genitourinario, except: [:index, :show, :destroy]
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
          end
        end
      end
    end
  end

  namespace :medical do
    resources :patients do
      resources :historia_medicas, except: [:destroy] do
        resources :print, except: [:index, :new, :show, :create, :edit, :update, :destroy] do
          collection do
            get 'single'
            get 'formulacion'
          end
        end
      end
    end
  end
end

app/controllers/fisio/clinic_histories_controller.rb
module Fisio
  class ClinicHistoriesController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history, only: [:edit, :update]

    def index
      @histories = @patient.historia_clinicas.order('created_at desc')
      .paginate(page: params[:page], per_page: 15)
    end

    def new
      @history = @patient.historia_clinicas.new
      @history.build_prenatale
      @history.build_perinatale
      @history.build_postnatale
    end

    def edit
      @history.build_prenatale if @history.prenatale.nil?
      @history.build_perinatale if @history.perinatale.nil?
      @history.build_postnatale if @history.postnatale.nil?
    end

    def create
      @history = HistoriaClinica.new(history_params)
      if @history.save
        flash[:notice] = "Historia clínica creada"
        redirect_to edit_fisio_patient_clinic_history_path(@patient, @history)
      else
        render :new
      end
    end

    def update
      if @history.update(history_params)
        flash[:notice] = "Información actualizada"
        redirect_to edit_fisio_patient_clinic_history_path(@patient, @history)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:id])
    end

    # parametros fuertes
    def history_params
      params.require(:historia_clinica).permit(:id, :paciente_id,
        :antecedentes_personales, :cirugias, :examenes_clinicos, :embarazos,
        :partos, :cesarea, :hijos_vivos, :abortos, :fum, :embarazo_actual,
        :medicamentos, :antecedentes_familiares, :motivo_consulta, :tiempo_gestacion,
        :riesgo_embarazo, :riesgo_embarazo_razon, :patologicos, :hospitalarios,
        :alergicos, :ayudas_previas,
        prenatale_attributes: [:id, :embarazo_riesgo,
          :planeado, :controles, :amenaza_aborto, :print],
        perinatale_attributes: [:id, :nacimiento,
          :cesarias, :vaginal, :print],
        postnatale_attributes: [:id, :complicaciones,
          :lactancia_exclusiva, :print])
    end
  end
end

app/controllers/fisio/desarrollo_motores_controller.rb
module Fisio
  class DesarrolloMotoresController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    before_action :set_motore, except: [:new, :create]

    def new
      @motores = @history.build_desarrollo_motor
    end

    def edit
    end

    def create
      @motores =  DesarrolloMotor.new(motore_params)
      if @motores.save
        flash[:notice] = 'Registro creado'
        redirect_to edit_fisio_patient_clinic_history_desarrollo_motore_path(@patient, @history, @motores)
      else
        render :new
      end
    end

    def update
      if @motores.update(motore_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_desarrollo_motore_path(@patient, @history, @motores)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    def set_motore
      if params[:id].nil?
        @motores =  @history.desarrollo_motor 
      else
        @motores = DesarrolloMotor.find(params[:id])
      end
    end

    def motore_params
      params.require(:desarrollo_motor).permit(:id, :historia_clinica_id, :centro_cefalico,
        :sedente, :rolado, :gateo, :bipedo, :marcha, :adicion, :antecedentes_psicosociales,
        :nucleo_familiar, :escolaridad, :habitos, :observacion)
    end
  end
end

app/controllers/fisio/evoluciones_controller.rb
module Fisio
  class EvolucionesController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_evolucion, except: [:new, :create, :index]

    def index
      @evoluciones = @patient.evolucions.order(created_at: :desc).paginate(page: params[:page], per_page: params[:per_page])
    end

    def new
      @evolucion = @patient.evolucions.new
    end

    def edit
    end

    def create
      @evolucion =  @patient.evolucions.new(evolucion_params)
      if @evolucion.save
        flash[:notice] = 'Registro creado'
        redirect_to fisio_patient_evoluciones_path(@patient)
      else
        render :new
      end
    end

    def update
      if @evolucion.update(evolucion_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_evolucione_path(@patient, @evolucion)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    def set_evolucion
      @evolucion = @patient.evolucions.find(params[:id])
    end

    def evolucion_params
      params.require(:evolucion).permit(:id, :paciente_id, :descripcion, :creation_date, :is_important)
    end
  end
end

app/controllers/fisio/patients_controller.rb
module Fisio
  class PatientsController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient, except: [:new, :create]

    # crear nuevo paciente
    def new
      @patient = current_usuario.pacientes.new
    end

    def create
      @patient = Paciente.new(patient_params)
      if @patient.save
        flash[:notice] = "Paciente creado correctamente"
        redirect_to edit_fisio_patient_path(@patient)
      else
        render :new
      end
    end

    def show
    end

    # formulario de edición
    def edit
    end

    # edición de datos
    def update
      if @patient.update(patient_params)
        flash[:notice] = "Paciente editado"
        redirect_to edit_fisio_patient_path(@patient)
      else
        render :edit
      end
    end

    private

    def set_patient
      @patient = current_usuario.pacientes.find(params[:id])
    end

    def patient_params
      params.require(:paciente).permit(:id, :usuario_id, :estado_civil_id,
      :fecha_actual, :direccion, :edad, :genero, :telefono, :movil, :rh, :membership_id,
      :profesion, :nombre_acompanante, :movil_acompanante, :remitido_por, :eps, :email,
      :type_document_id, :telefono, :escolaridad, :documento, :nombre, :fecha_nacimiento)
    end
  end
end

app/controllers/fisio/print_controller.rb
module Fisio
  class PrintController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    
    def single
      respond_to do |format|
        format.html
        format.pdf do
          render template: "fisio/clinic_histories/print", pdf: "#{@patient.nombre}-Historia Clinica-#{@history.created_at.strftime('%d-%m-%Y')}",
          encoding: 'utf-8', :margin => {:bottom => 25}, footer:  { html: {   template:'shared/pdf_footer' } }
        end
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end
  end
end

app/controllers/fisio/pruebas_especiales_controller.rb
module Fisio
  class PruebasEspecialesController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    
    def edit
      @history.pruebas_especiales_pacientes.build if @history.pruebas_especiales_pacientes.count == 0
      @history.pruebas_flexibilidad_pacientes.build if @history.pruebas_flexibilidad_pacientes.count == 0
    end

    def update
      if @history.update(pruebas_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_pruebas_especiale_path(@patient, @history, 1)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    # parámetros fuertes
    def pruebas_params
      params.require(:historia_clinica).permit(:id,
        pruebas_especiales_pacientes_attributes: [:id, :pruebas_especial_id, :zona, :derecho,
          :izquierdo, :observaciones, :_destroy],
        pruebas_flexibilidad_pacientes_attributes: [:id, :pruebas_flexibilidad_id,
         :musculo, :positivo, :negativo, :leve, :moderado, :severo, :_destroy])
    end
  end
end

app/controllers/fisio/remision_externa_controller.rb
module Fisio
  class RemisionExternaController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    before_action :set_remi, except: [:new, :create]

    def new
      @remi = @history.build_diagnostico
    end

    def edit
    end

    def create
      @remi =  Diagnostico.new(diagnostico_params)
      if @remi.save
        flash[:notice] = 'Registro creado'
        redirect_to edit_fisio_patient_clinic_history_remision_externa_path(@patient, @history, @remi)
      else
        render :new
      end
    end

    def update
      if @remi.update(diagnostico_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_remision_externa_path(@patient, @history, @remi)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    # setea sistema cardiopulmonar
    def set_remi
      if params[:id].nil?
        @remi =  @history.diagnostico 
      else
        @remi = Diagnostico.find(params[:id])
      end
    end

    # parámetros fuertes
    def diagnostico_params
      params.require(:diagnostico).permit(:id, :historia_clinica_id, :diagnostico,
        :recomendacion, :restriccion, :sugerencia_terapeutica, :objetivo_general, :objetivo_especifico)
    end
  end
end

app/controllers/fisio/sistema_cardiopulmonar_controller.rb
module Fisio
  class SistemaCardiopulmonarController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    before_action :set_cardio, except: [:new, :create]

    def new
      @cardio = @history.build_sistema_cardiopulmonar
    end

    def edit
    end

    def create
      @cardio =  SistemaCardiopulmonar.new(cardio_params)
      if @cardio.save
        flash[:notice] = 'Registro creado'
        redirect_to edit_fisio_patient_clinic_history_sistema_cardiopulmonar_path(@patient, @history, @cardio)
      else
        render :new
      end
    end

    def update
      if @cardio.update(cardio_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_sistema_cardiopulmonar_path(@patient, @history, @cardio)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    # setea sistema cardiopulmonar
    def set_cardio
      if params[:id].nil?
        @cardio =  @history.sistema_cardiopulmonar 
      else
        @cardio = SistemaCardiopulmonar.find(params[:id])
      end
    end

    # parámetros fuertes
    def cardio_params
      params.require(:sistema_cardiopulmonar).permit(:id, :historia_clinica_id, :pa,
        :fc, :fr, :sao2, :ausc_pulmonar, :ausc_cardiaca)
    end
  end
end

app/controllers/fisio/sistema_genitourinario_controller.rb
module Fisio
  class SistemaGenitourinarioController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    before_action :set_genito, except: [:new, :create]

    def new
      @genito = @history.build_sistema_genitourinario
    end

    def edit
    end

    def create
      @genito =  SistemaGenitourinario.new(genito_params)
      if @genito.save
        flash[:notice] = 'Registro creado'
        redirect_to edit_fisio_patient_clinic_history_sistema_genitourinario_path(@patient, @history, @genito)
      else
        render :new
      end
    end

    def update
      if @genito.update(genito_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_sistema_genitourinario_path(@patient, @history, @genito)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    # setea sistema genitourinario
    def set_genito
      @genito = SistemaGenitourinario.find(params[:id])
    end

    # parámetros fuertes
    def genito_params
      params.require(:sistema_genitourinario).permit(:id, :historia_clinica_id, :indemne, :incontinencia,
        :prolapsos, :diastasis, :trastornos, :incontinencia_fecal, :estrenimiento, :disfuncion_sexual, :observaciones)
    end
  end
end

app/controllers/fisio/sistema_tegumentario_controller.rb
module Fisio
  class SistemaTegumentarioController < FisioController
    before_action :authenticate_usuario!
    before_action :set_patient
    before_action :set_history
    before_action :set_tegu, except: [:new, :create]

    def new
      @tegu = @history.build_sistema_tegumentario
    end

    def edit
    end

    def create
      @tegu = SistemaTegumentario.new(tegu_params)
      if @tegu.save
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_sistema_tegumentario_path(@patient, @history, @tegu)
      else
        render :edit
      end
    end

    def update
      if @tegu.update(tegu_params)
        flash[:notice] = 'Registro editado'
        redirect_to edit_fisio_patient_clinic_history_sistema_tegumentario_path(@patient, @history, @tegu)
      else
        render :edit
      end
    end

    private

    # setear paciente atual
    def set_patient
      @patient = current_usuario.pacientes.find(params[:patient_id])
    end

    # setear historia clinica
    def set_history
      @history = HistoriaClinica.find(params[:clinic_history_id])
    end

    def set_tegu
      @tegu = SistemaTegumentario.find(params[:id])
    end

    # parametros fuertes
    def tegu_params
      params.require(:sistema_tegumentario).permit(:id, :historia_clinica_id,
        :color, :estado, :tumefaccion, :escaras, :heridas, :cicatriz)
    end
  end
end

app/views/fisio/clinic_histories/_form.html.haml
%script
  $( document ).ready(function() {
  //LLama al datepicker y lo traduce
  $( ".datepicker" ).datepicker({
  changeMonth: true,
  changeYear: true,
  format: 'yyyy-mm-dd'
  });
  date_picker_es();
  //Inicializa la librería Jquery Chosen, para los selects
  //$(".chosen-selects").chosen();
  });

= nested_form_for @history, url: {action: @history.id.nil? ? 'create' : 'update'}, html: {class: ""} do |f|
  .box-body.form-to-clinic-h
    =f.hidden_field :paciente_id, value: @patient.id
    .row.text-center
      .col-md-12.col-sm-12.col-xs-12
        .form-group
          =f.label :motivo_consulta
          =f.text_area :motivo_consulta, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :embarazos
          =f.text_field :embarazos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :partos
          =f.text_field :partos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :cesarea, 'Cesárea'
          =f.text_field :cesarea, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :hijos_vivos
          =f.text_field :hijos_vivos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :embarazo_actual
          =f.text_field :embarazo_actual, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :fum
          =f.text_field :fum, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :abortos
          =f.text_field :abortos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :medicamentos
          =f.text_area :medicamentos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :cirugias, 'Cirugías'
          =f.text_area :cirugias, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :antecedentes_familiares
          =f.text_area :antecedentes_familiares, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :antecedentes_personales
          =f.text_area :antecedentes_personales, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :examenes_clinicos, 'Exámenes clínicos'
          =f.text_area :examenes_clinicos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :tiempo_gestacion, 'Tiempo de gestación'
          =f.text_field :tiempo_gestacion, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :riesgo_embarazo, 'Riesgo durante el embarazo'
          .radio{style: 'height: 34px'}
            %label
              = f.radio_button :riesgo_embarazo, true
              Si
          .radio{style: 'height: 34px'}
            %label
              = f.radio_button :riesgo_embarazo, false
              No
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :riesgo_embarazo_razon, 'Por Qué?'
          =f.text_area :riesgo_embarazo_razon, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :patologicos, 'Patológicos'
          =f.text_area :patologicos, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :hospitalarios
          =f.text_area :hospitalarios, class: 'form-control'
      .col-md-4.col-sm-4.col-xs-12
        .form-group
          =f.label :alergicos, 'Alérgicos'
          =f.text_area :alergicos, class: 'form-control'

    .row.text-center
      %hr
      %h3 Antecedentes prenatales
      = f.fields_for :prenatale do |prenatale_form|
        .col-md-12.col-sm-12.col-xs-12
          .form-group.pull-left
            =prenatale_form.label :print, 'Agregar a impresión?'
            =prenatale_form.check_box :print
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = prenatale_form.label :embarazo_riesgo, 'Embarazo alto riesgo'
            .radio
              %label
                = prenatale_form.radio_button :embarazo_riesgo, true
                Si
            .radio
              %label
                = prenatale_form.radio_button :embarazo_riesgo, false
                No
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = prenatale_form.label :planeado
            .radio
              %label
                = prenatale_form.radio_button :planeado, true
                Si
            .radio
              %label
                = prenatale_form.radio_button :planeado, false
                No
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = prenatale_form.label :controles
            .radio
              %label
                = prenatale_form.radio_button :controles, true
                Si
            .radio
              %label
                = prenatale_form.radio_button :controles, false
                No
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = prenatale_form.label :amenaza_aborto, 'Amenaza de aborto'
            .radio
              %label
                = prenatale_form.radio_button :amenaza_aborto, true
                Si
            .radio
              %label
                = prenatale_form.radio_button :amenaza_aborto, false
                No

    .row.text-center
      %hr
      %h3 Antecedentes perinatales:
      = f.fields_for :perinatale do |perinatale_form|
        .col-md-12.col-sm-12.col-xs-12
          .form-group.pull-left
            =perinatale_form.label :print, 'Agregar a impresión?'
            =perinatale_form.check_box :print
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = perinatale_form.label :nacimiento, 'Número de semanas al nacimiento'
            = perinatale_form.text_field :nacimiento, class: 'form-control', type: 'number'
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = perinatale_form.label :cesarias
            .radio
              %label
                = perinatale_form.radio_button :cesarias, true
                Si
            .radio
              %label
                = perinatale_form.radio_button :cesarias, false
                No
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = perinatale_form.label :vaginal
            .radio
              %label
                = perinatale_form.radio_button :vaginal, true
                Si
            .radio
              %label
                = perinatale_form.radio_button :vaginal, false
                No

    .row.text-center
      %hr
      %h3 Antecedentes postnatales:
      = f.fields_for :postnatale do |postnatale_form|
        .col-md-12.col-sm-12.col-xs-12
          .form-group.pull-left
            =postnatale_form.label :print, 'Agregar a impresión?'
            =postnatale_form.check_box :print
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = postnatale_form.label :complicaciones
            .radio
              %label
                = postnatale_form.radio_button :complicaciones, true
                Si
            .radio
              %label
                = postnatale_form.radio_button :complicaciones, false
                No
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            = postnatale_form.label :lactancia_exclusiva
            .radio
              %label
                = postnatale_form.radio_button :lactancia_exclusiva, true
                Si
            .radio
              %label
                = postnatale_form.radio_button :lactancia_exclusiva, false
                No




    .text-center
      %br
      =f.submit class: 'btn btn-primary'
      %br
      %br


-if current_usuario.can_edit == false && !@history.new_record?
  %script
    disableInputs();

app/views/fisio/clinic_histories/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Historia clínica
    <small>Editar historia</small>
    <%= render partial: 'fisio/layouts/historia_actual' %>
  </h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header"></div>
        <!-- /.box-header -->
        <div class="box-body">
          <%-if @history.errors.count > 0 %>
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4><i class="icon fa fa-ban"></i> Error!</h4>
              <%= @history.errors.full_messages.to_sentence%>
            </div>
          <%end%>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>  

app/views/fisio/clinic_histories/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Historias Clínicas de <%= @patient.nombre %>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Historias</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example2" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th>Id</th>
              <th>Nombre</th>
              <th>Fecha de creación</th>
              <th>Opciones</th>
            </tr>
            </thead>
            <tbody>
              <%-@histories.each do |history|%>
                <tr>
                  <td><%= history.id%></td>
                  <td><%= @patient.nombre %></td>
                  <td><%= history.created_at.strftime("%Y-%m-%d %I:%M %p") %></td>
                  <td>
                    <a href="<%= edit_fisio_patient_clinic_history_path(@patient, history) %>">
                      <i class="fa fa-fw fa-search"></i>  
                    </a>
                    <a href="<%= single_fisio_patient_clinic_history_print_index_path(@patient, history, :format => :pdf)%>" title="Imprimir historia" target="_blank">
                      <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                  </td>
                </tr>
              <%end%>
            </tbody>
          </table>
          <br>
          <div class="row">
            <div class="col-md-3">
              <a href="<%= new_fisio_patient_clinic_history_path(@patient)%>" class="btn btn-primary">
                Crear
              </a>
            </div>
            <div class="col-md-9">
              <div class="pull-right">
                <%= will_paginate @histories, renderer: BootstrapPagination::Rails %>    
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

<script>
$(function () {
  $('#example2').dataTable({
    'paging'      : false,
    'lengthChange': false,
    'searching'   : false,
    'ordering'    : true,
    'info'        : true,
    'autoWidth'   : false
  })
})
</script>

app/views/fisio/clinic_histories/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Historia clínica
    <small>Nueva historia</small>
  </h1>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header"></div>
        <!-- /.box-header -->
        <div class="box-body">
          <%-if @history.errors.count > 0 %>
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              <h4><i class="icon fa fa-ban"></i> Error!</h4>
              <%= @history.errors.full_messages.to_sentence%>
            </div>
          <%end%>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>  